BeachMall/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from BeachMall import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('member/', include("member.urls")),
    path('product/', include("product.urls")),
    path('cart/', include("cart.urls")),
    path('wishlist/', include("wishlist.urls")),
    path('order/', include("order.urls")),
    path('survey/', include("survey.urls")),
    path('recommend/', include("recommend.urls")),
    path('refund/', include("refund.urls")),
    path('reviewboard/', include("reviewboard.urls")),
    path('noticeboard/', include("noticeboard.urls")),
    path('qnaboard/', include("qnaboard.urls")),
    path('search/', include('search_app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls.conf import path
from cart import views

app_name = "cart"

urlpatterns = [
    path("cart", views.CartView.as_view(), name="cart"),
    path("cartins", views.CartInsView.as_view(), name="cartins"),
    path("cartdel", views.CartDelView.as_view(), name="cartdel"),
    path("cartmod", views.CartModView.as_view(), name="cartmod"),
]

member/urls.py
from django.urls.conf import path
from member import views

app_name = "member"

urlpatterns = [
    path("login",views.LoginView.as_view(),name="login"),
    path('memberjoin', views.JoinView.as_view() ,name="memberjoin"),
    path("idconfirm", views.IdConfirmView.as_view(), name="idconfirm"), 
    path("telconfirm", views.TelConfirmView.as_view(), name="telconfirm"),
    path("logout", views.LogoutView.as_view(), name ="logout"),
    path("delete", views.DeleteView.as_view(), name="delete"), 
    path("modify", views.ModifyView.as_view(), name="modify"),
    path("modifypro", views.ModifyProView.as_view(), name="modifypro"),
    path("index",views.IndexView.as_view(), name="index"),
    path("myorderlist",views.MyOrderListView.as_view(), name="myorderlist"),
    path("myorderdetail",views.MyOrderDetailView.as_view(), name="myorderdetail"),
    path("mybeach",views.MyBeachView.as_view(), name="mybeach"),
    path("papup",views.PapUpView.as_view(), name="papup"),
]

product/urls.py
from django.urls.conf import path
from product import views

app_name = "product"

urlpatterns = [
    path("productDetail", views.ProductDetailView.as_view(), name="productDetail"),
    path("productCategory", views.ProductCategoryView.as_view(), name="productCategory"),
    path("productList", views.ProductListView.as_view(), name="productList"),
    path("waterRocket", views.WaterRocketView.as_view(), name="waterrocket"),
    ]

reviewboard/urls.py
from django.urls.conf import path
from reviewboard import views

app_name = "reviewboard"

urlpatterns = [
    path("reviewWrite", views.ReviewWriteView.as_view(), name="reviewWrite"),
    path("reviewModify", views.ReviewModifyView.as_view(), name="reviewModify"),
    path("reviewDelete", views.ReviewDeleteView.as_view(), name="reviewDelete"),
    path("myReviewList", views.MyReviewList.as_view(), name="myReviewList"),
    ]

wishlist/urls.py
from django.urls.conf import path
from wishlist import views

app_name = "wishlist"

urlpatterns = [
    path("wish", views.WishView.as_view(), name="wish"),
    path("wishdel", views.WishDelView.as_view(), name="wishdel"),
    path("wishins", views.WishInsView.as_view(), name="wishins"),
]

product/models.py
from django.db import models
from product.choice import BRAND_CHOICE

# Create your models here.
class Product(models.Model):
    prodNum = models.BigAutoField(verbose_name="상품번호", primary_key=True)
    prodName = models.CharField(verbose_name="상품명", null=False, max_length=1000)
    prodStock = models.IntegerField(verbose_name="재고", null=False)
    prodPrice = models.BigIntegerField(verbose_name="가격", null=False)
    prodInfo = models.TextField(verbose_name="상품 설명", null=False, max_length=30000)
    prodThumbnail = models.ImageField(verbose_name="썸네일", null=False, upload_to="products")
    prodImage1 = models.ImageField(verbose_name="이미지1", null=False, upload_to="products")
    prodImage2 = models.ImageField(verbose_name="이미지2", null=False, upload_to="products")
    searchCount = models.BigIntegerField(verbose_name="조회수", null=False)
    status = models.SmallIntegerField(verbose_name="상태", null=False)
    brand = models.CharField(verbose_name="브랜드", null=False, max_length=100, choices=BRAND_CHOICE)

product/views.py
from django.shortcuts import render
from django.views.generic.base import View
from django.template import loader
from django.http.response import HttpResponse
from product.models import Product
import logging
from product.choice import BRAND_CHOICE
from reviewboard.models import Reviewboard
from recommend.models import Recommend
from static.myfunction import getRecentProduct
from django.core.exceptions import ObjectDoesNotExist
import json

# Create your views here.
logger = logging.getLogger( __name__ )

PAGE_SIZE = 15
PAGE_BLOCK = 5

# 상품 상세 정보 페이지
class ProductDetailView(View):
    def get(self, request):
        template = loader.get_template("productDetail.html")
        prodNum = request.GET["prodNum"]
        product = Product.objects.get(prodNum=prodNum)
        product.searchCount += 1
        product.save()
        
        #### 리뷰 게시판도 여기 출력 ###
        count = Reviewboard.objects.filter(prodNum=prodNum).count()
        
        pagenum = request.GET.get("pagenum")
        if not pagenum :
            pagenum = "1"
        pagenum = int(pagenum)
        
        start = (pagenum - 1) * int(PAGE_SIZE)      # (5 - 1) * 10    = 40    슬라이싱을 위해 0~10까지 잡기
        end = start + int(PAGE_SIZE)                # 40 + 10         = 50
        if end > count :
            end = count
        reviews = Reviewboard.objects.order_by("-reviewNum").filter(prodNum=prodNum)[start:end]
        number = count - (pagenum - 1) * int(PAGE_SIZE)
        
        startpage = pagenum // int(PAGE_BLOCK) * int(PAGE_BLOCK) + 1    # 9 // 10 * 10 + 1     = 1
        if pagenum % int(PAGE_BLOCK) == 0:
            startpage -= int(PAGE_BLOCK)
        endpage = startpage + int(PAGE_BLOCK) - 1                       # 1 + 10 - 1           = 10
        pagecount = count // int(PAGE_SIZE)
        if count % int(PAGE_SIZE) > 0 :
            pagecount += 1
        if endpage > pagecount:
            endpage = pagecount
        pages = range(startpage, endpage + 1)
        
        userId = request.session.get("memid")
        if userId:
            logger.info("id:"+userId+",prodNum:"+str(product.prodNum)+",prodName:"+product.prodName+",brand:"+product.brand+",,from:"+request.META["HTTP_REFERER"]+",to:"+request.get_full_path())
        
        recentProducts = getRecentProduct(userId)
        
        context = {
            "count" : count,
            "reviews" : reviews,
            "pagenum" : pagenum,
            "number" : number,
            "pages" : pages,
            "startpage" : startpage,
            "endpage" : endpage,
            "pageblock" : PAGE_BLOCK,
            "pagecount" : pagecount,
            "product" : product,
            "recentProducts" : recentProducts,
            }
        return HttpResponse(template.render(context, request))
    def post(self, request):
        pass

# 상품 전체 리스트 페이지    
class ProductCategoryView(View):
    def get (self,request):
        template=loader.get_template("productCategory.html")
        
        minamount = request.GET.get("minamount")
        maxamount = request.GET.get("maxamount")
        
        if minamount != None and maxamount != None:
            count = Product.objects.filter(prodPrice__gte=minamount).filter(prodPrice__lte=maxamount).count()
        else:
            count = Product.objects.all().count()
        
        pagenum = request.GET.get( "pagenum" )
        if not pagenum :
            pagenum = "1"
        pagenum = int( pagenum )
        
        start = ( pagenum - 1 ) * int(PAGE_SIZE)          # ( 5 - 1 ) * 10 + 1     41
        end = start + int(PAGE_SIZE)                      # 41 + 10 - 1            50
        if end > count :
            end = count
        
        if minamount != None and maxamount != None:
            products = Product.objects.filter(prodPrice__gte=minamount).filter(prodPrice__lte=maxamount).order_by("-prodNum" )[start:end]
        else:
            products = Product.objects.all().order_by("-prodNum" )[start:end] # jsp와 다르게 슬라이싱해서 씀
        number = count - ( pagenum - 1 ) * int(PAGE_SIZE )
        
        startpage = pagenum // int(PAGE_BLOCK) * int(PAGE_BLOCK) + 1       # 9 // 10 * 10 + 1    1
        if pagenum % int(PAGE_BLOCK) == 0:
            startpage -= int(PAGE_BLOCK)
        endpage = startpage + int(PAGE_BLOCK) - 1                         # 1 + 10 -1           10
        pagecount = count // int(PAGE_SIZE)
        if count % int(PAGE_SIZE) > 0 :
            pagecount += 1
        if endpage > pagecount :
            endpage = pagecount
        pages = range( startpage, endpage+1 )
        
        lastProducts = Product.objects.order_by("-prodNum")[0:5]

        recommends = []
        userId = request.session.get("memid")
        if userId:
            try:
                recos = Recommend.objects.filter(userId=userId).filter(status="gender_age").order_by("-recommendNum").first().prodList
                gender_age_recos = json.loads(recos)
                recommends = [Product.objects.get(prodNum=prodNum) for prodNum in gender_age_recos]
            except (ObjectDoesNotExist, AttributeError):
                recommends = []
        
        userId = request.session.get("memid")
        recentProducts = getRecentProduct(userId)
        
        context={
            "brands" : BRAND_CHOICE,
            "count" : count,
            "products" : products,
            "pagenum" : pagenum,
            "number" : number,
            "pages" : pages,
            "startpage" : startpage,
            "endpage" : endpage,
            "pageblock" : PAGE_BLOCK,
            "pagecount" : pagecount,
            "recommends" : recommends,
            "lastProducts" : lastProducts,
            "recentProducts" : recentProducts,
            "minamount" : minamount,
            "maxamount" : maxamount,
            }
        if userId:
            logger.info("id:"+userId+",,,,pageNum:"+str(pagenum)+",from:"+request.META["HTTP_REFERER"]+",to:"+request.get_full_path())
        return HttpResponse(template.render( context ,request))
    def post(self,request):
        pass

# 상품 물로켓 리스트 페이지
class WaterRocketView(View):
    def get (self,request):
        template=loader.get_template("waterRocket.html")
        minamount = request.GET.get("minamount")
        maxamount = request.GET.get("maxamount")
        
        if minamount != None and maxamount != None:
            count = Product.objects.filter(prodPrice__gte=minamount).filter(prodPrice__lte=maxamount).count()
        else:
            count = Product.objects.all().count()
            
        pagenum = request.GET.get( "pagenum" )
        if not pagenum :
            pagenum = "1"
        pagenum = int( pagenum )
        
        start = ( pagenum - 1 ) * int(PAGE_SIZE)          # ( 5 - 1 ) * 10 + 1     41
        end = start + int(PAGE_SIZE)                      # 41 + 10 - 1            50
        if end > count :
            end = count
            
        if minamount != None and maxamount != None:
            products = Product.objects.filter(prodPrice__gte=minamount).filter(prodPrice__lte=maxamount).order_by("-prodNum" )[start:end]
        else:
            products = Product.objects.all().order_by("-prodNum" )[start:end] # jsp와 다르게 슬라이싱해서 씀
        number = count - ( pagenum - 1 ) * int(PAGE_SIZE )
        
        startpage = pagenum // int(PAGE_BLOCK) * int(PAGE_BLOCK) + 1       # 9 // 10 * 10 + 1    1
        if pagenum % int(PAGE_BLOCK) == 0:
            startpage -= int(PAGE_BLOCK)
        endpage = startpage + int(PAGE_BLOCK) - 1                         # 1 + 10 -1           10
        pagecount = count // int(PAGE_SIZE)
        if count % int(PAGE_SIZE) > 0 :
            pagecount += 1
        if endpage > pagecount :
            endpage = pagecount
        pages = range( startpage, endpage+1 )

        lastProducts = Product.objects.order_by("-prodNum")[0:5]
        
        recommends = []
        userId = request.session.get("memid")
        if userId:
            try:
                recos = Recommend.objects.filter(userId=userId).filter(status="gender_age").order_by("-recommendNum").first().prodList
                gender_age_recos = json.loads(recos)
                recommends = [Product.objects.get(prodNum=prodNum) for prodNum in gender_age_recos]
            except (ObjectDoesNotExist, AttributeError):
                recommends = []
        
        userId = request.session.get("memid")
        recentProducts = getRecentProduct(userId)
        
        context={
            "recommends":recommends,
            "lastProducts":lastProducts,
            "brands" : BRAND_CHOICE,
            "count" : count,
            "products" : products,
            "number" : number,
            "pages" : pages,
            "startpage" : startpage,
            "endpage" : endpage,
            "pageblock" : PAGE_BLOCK,
            "pagecount" : pagecount,
            "recentProducts" : recentProducts,
            }
        if userId:
            logger.info("id:"+userId+",,,,pageNum:"+str(pagenum)+",from:"+request.META["HTTP_REFERER"]+",to:"+request.get_full_path())
        return HttpResponse(template.render( context ,request))
    def post(self,request):
        pass

# 상품 브랜드별 리스트 페이지    
class ProductListView(View):
    def get (self,request):
        template = loader.get_template( "productList.html" )
        
        brand = request.GET["brand"]
        
        minamount = request.GET.get("minamount")
        maxamount = request.GET.get("maxamount")
        
        if minamount != None and maxamount != None:
            count = Product.objects.filter(brand=brand).filter(prodPrice__gte=minamount).filter(prodPrice__lte=maxamount).count()
        else:
            count = Product.objects.filter(brand=brand).count()
        
        pagenum = request.GET.get( "pagenum" )
        if not pagenum :
            pagenum = "1"
        pagenum = int( pagenum )
        
        start = ( pagenum - 1 ) * int(PAGE_SIZE)          # ( 5 - 1 ) * 10 + 1     41

product/templates/productCategory.html
{% extends "base.html"%}
{% load static %}
{% load humanize %}
{% load mathfilters %}
{% block content %}

<script type="text/javascript">
	function setPriceRange(){
		loca = location.href.split("?")
		let minamount = document.getElementById("minamount").value.replace("원", "");
		let maxamount = document.getElementById("maxamount").value.replace("원", "");
		location.href = loca[0]+"?minamount="+minamount+"&maxamount="+maxamount;
	}
</script>

<!-- big category Section Begin -->
<section class="breadcrumb-section set-bg"
	data-setbg="{% static 'images/beach2.png' %}">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center">
				<div class="breadcrumb__text">
					<h2 style="color: black;">Beach product</h2>
					<div class="breadcrumb__option">
						<a href="{% url 'member:index' %}" style="color: black;">Home</a>
						<span style="color: black;">productCategory</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- big category Section End -->

<!-- Product Section Begin -->
<section class="product spad">
	<div class="container">
		<div class="row">
			<div class="col-lg-3 col-md-5">
				<div class="sidebar">
					<div class="sidebar__item">
						<h4>Price</h4>
						<div class="price-range-wrap">
							<div class="price-range ui-slider ui-corner-all ui-slider-horizontal ui-widget ui-widget-content" data-min="10" data-max="5000000">
								<div class="ui-slider-range ui-corner-all ui-widget-header"></div>
								<span tabindex="0" class="ui-slider-handle ui-corner-all ui-state-default"></span>
								<span tabindex="0" class="ui-slider-handle ui-corner-all ui-state-default"></span>
							</div>
							<div class="range-slider">
								<div class="price-input">
									<input type="text" id="minamount" />
									<input type="text" id="maxamount" />
								</div>
								<input type="button" value="가격 범위 설정" onclick="setPriceRange()">
							</div>
						</div>
					</div>
					<div class="sidebar__item" style="width:240px;margin-right:0px;">
						<h4>Department</h4>
						<ul>
							{% for brand in brands %}
							<li><a href="{% url 'product:productList' %}?brand={{brand.0}}">{{brand.0}}</a></li>
							{% endfor %}
						</ul>
					</div>
				</div>
			</div>
			<div class="col-lg-9 col-md-7">
				{% if recommends %}
				<div class="product__discount">
					<div class="section-title product__discount__title">
						<h2>Sale Off</h2>
					</div>
					<div class="row">
						<div class="product__discount__slider owl-carousel">
							{% for recommend in recommends %}
							<div class="col-lg-4">
								<div class="product__discount__item">
									<div class="product__discount__item__pic set-bg"
										data-setbg="{{recommend.prodImage1.url}}">
										<div class="product__discount__percent">-10%</div>
										<ul class="product__item__pic__hover">
											<li>
												<a href="{% url 'wishlist:wishins' %}?userId={{request.session.memid}}&prodNum={{recommend.prodNum}}">
													<i class="fa fa-heart"></i>
												</a>
											</li>
											<li>
												<a href="{% url 'cart:cartins' %}?userId={{request.session.memid}}&prodNum={{recommend.prodNum}}&buyCount=1">
													<i class="fa fa-shopping-cart"></i>
												</a>
											</li>
										</ul>
									</div>
									<div class="product__discount__item__text">
										<span>{{recommend.brand}}</span>
										<h5>
											<a href="{% url 'product:productDetail' %}?prodNum={{recommend.prodNum}}">{{recommend.prodName}}</a>
										</h5>
										<div class="product__item__price">
											{{recommend.prodPrice|intcomma }}원 <span>{{recommend.prodPrice|mul:1.1|floatformat:"0"|intcomma }}원</span>
										</div>
									</div>
								</div>
							</div>
							{% endfor %}
						</div>
					</div>
				</div>
				{% endif %}
				<div class="filter__item">
					<div class="row">
						<div class="col-lg-4 col-md-5">
							<div class="filter__sort">
								<span>Sort By</span>
								<select>
									<option value="0">기본 정렬</option>
								</select>
							</div>
						</div>
						<div class="col-lg-4 col-md-4">
							<div class="filter__found">
								<h6>
									<span>{{count}}</span> Products found
								</h6>
							</div>
						</div>
						<div class="col-lg-4 col-md-3">
							<div class="filter__option">
								<span class="icon_grid-2x2"></span> <span class="icon_ul"></span>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					{% for product in products %}
					<div class="col-lg-4 col-md-6 col-sm-6">
						<div class="product__item">
							<div class="product__item__pic set-bg"
								data-setbg="{{product.prodThumbnail.url}}">
								<ul class="product__item__pic__hover">
									<li><a href="{% url 'wishlist:wishins' %}?userId={{request.session.memid}}&prodNum={{product.prodNum}}"><i class="fa fa-heart"></i></a></li>
									<li><a href="{% url 'cart:cartins' %}?userId={{request.session.memid}}&prodNum={{product.prodNum}}&buyCount=1"><i class="fa fa-shopping-cart"></i></a></li>
								</ul>
							</div>
							<div class="product__item__text">
								<h6>
									<a href="{% url 'product:productList' %}?brand={{product.brand}}">{{product.brand}}</a>
								</h6>
								<h6>
									<a href="{% url 'product:productDetail' %}?prodNum={{product.prodNum}}">{{product.prodName}}</a>
								</h6>
								<h5>{{product.prodPrice|intcomma}}원</h5>
							</div>
						</div>
					</div>
					{% endfor %}
				</div>
				<div class="product__pagination">
					{% if startpage > pageblock %}
						<a href="{% url 'product:productCategory' %}?pagenum={{startpage|sub:pageblock}}"><i class="fa fa-long-arrow-left"></i></a>
					{% endif %}
					{% for page in pages %}
						{% if pagenum == page %}
							<a style="color:black;">{{page}}</a>
						{% else %}
							<a href="{% url 'product:productCategory' %}?pagenum={{page}}">{{page}}</a>
						{% endif %}
					{% endfor %}
					{% if endpage < pagecount %}
						<a href="{% url 'product:productCategory' %}?pagenum={{startpage|add:pageblock}}"><i class="fa fa-long-arrow-right"></i></a>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
</section>
<!-- Product Section End -->
{%endblock%}

product/templates/productList.html
{% extends "base.html"%}
{% load static %}
{% load humanize %}
{% load mathfilters %}
{%block content %}

<script type="text/javascript">
	function setPriceRange(){
		loca = location.href.split("&")
		let minamount = document.getElementById("minamount").value.replace("원", "");
		let maxamount = document.getElementById("maxamount").value.replace("원", "");
		location.href = loca[0]+"&minamount="+minamount+"&maxamount="+maxamount;
	}
</script>

<!-- big category Section Begin -->
<section class="breadcrumb-section set-bg" data-setbg="{% static 'images/beach2.png' %}">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center">
				<div class="breadcrumb__text">
					<h2 style="color: black;">Beach product</h2>
					<div class="breadcrumb__option">
						<a href="{% url 'member:index' %}" style="color: black;">Home</a>
						<span style="color: black;">productCategory</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- big category Section End -->

<!-- Product Section Begin -->
<section class="product spad">
	<div class="container">
		<div class="row">
			<div class="col-lg-3 col-md-5">
				<div class="sidebar">
					<div class="sidebar__item">
						<h4>Price</h4>
						<div class="price-range-wrap">
							<div class="price-range ui-slider ui-corner-all ui-slider-horizontal ui-widget ui-widget-content" data-min="10" data-max="5000000">
								<div class="ui-slider-range ui-corner-all ui-widget-header"></div>
								<span tabindex="0"
									class="ui-slider-handle ui-corner-all ui-state-default"></span>
								<span tabindex="0"
									class="ui-slider-handle ui-corner-all ui-state-default"></span>
							</div>
							<div class="range-slider">
								<div class="price-input">
									<input type="text" id="minamount" />
									<input type="text" id="maxamount" />
								</div>
								<input type="button" value="가격 범위 설정" onclick="setPriceRange()">
							</div>
						</div>
					</div>
					<div class="sidebar__item" style="width:240px;margin-right:0px;">
						<h4>Department</h4>
						<ul>
							{% for brand in brands %}
							<li><a href="{% url 'product:productList' %}?brand={{brand.0}}">{{brand.0}}</a></li>
							{% endfor %}
						</ul>
					</div>
					<div class="sidebar__item">
						<div class="latest-product__text">
							<h4>비치에 들어온 최신상품</h4>
							{% for lastProduct in lastProducts %}
							<div class="latest-product__slider owl-carousel">
								<div class="latest-prdouct__slider__item">
									<a href="{% url 'product:productDetail' %}?prodNum={{lastProduct.prodNum}}" class="latest-product__item">
										<div class="latest-product__item__pic">
											<img src="{{lastProduct.prodThumbnail.url}}" alt="" />
										</div>
										<div class="latest-product__item__text">
											<h6>{{lastProduct.prodName}}</h6>
											<h6>{{lastProduct.brand}}</h6>
											<span>{{lastProduct.prodPrice|intcomma }}원</span>
										</div>
									</a>
								</div>
							</div>
							{% endfor %}
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-9 col-md-7">
				<div class="filter__item">
					<div class="row">
						<div class="col-lg-4 col-md-5">
							<div class="filter__sort">
								<span>Sort By</span>
								<select>
									<option value="0">기본 정렬</option>
								</select>
							</div>
						</div>
						<div class="col-lg-4 col-md-4">
							<div class="filter__found">
								<h6>
									<span>{{count}}</span> Products found
								</h6>
							</div>
						</div>
						<div class="col-lg-4 col-md-3">
							<div class="filter__option">
								<span class="icon_grid-2x2"></span> <span class="icon_ul"></span>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					{% for product in products %}
					<div class="col-lg-4 col-md-6 col-sm-6">
						<div class="product__item">
							<div class="product__item__pic set-bg" data-setbg="{{product.prodThumbnail.url}}">
								<ul class="product__item__pic__hover">
									<li>
										<a href="{% url 'wishlist:wishins' %}?userId={{request.session.memid}}&prodNum={{product.prodNum}}">
											<i class="fa fa-heart"></i>
										</a>
									</li>
									<li>
										<a href="{% url 'cart:cartins' %}?userId={{request.session.memid}}&prodNum={{product.prodNum}}&buyCount=1">
											<i class="fa fa-shopping-cart"></i>
										</a>
									</li>
								</ul>
							</div>
							<div class="product__item__text">
								<h6>
									<a href="{% url 'product:productDetail' %}?prodNum={{product.prodNum}}">{{product.prodName}}</a>
								</h6>
								<h5>{{product.prodPrice|intcomma}}원</h5>
							</div>
						</div>
					</div>
					{% endfor %}
				</div>
				<div class="product__pagination">
					{% if startpage > pageblock %}
						<a href="{% url 'product:productList' %}?brand={{brand}}&pagenum={{startpage|sub:pageblock}}"><i class="fa fa-long-arrow-left"></i></a>
					{% endif %}
					{% for page in pages %}
						{% if pagenum == page %}
							<a style="color:black;">{{page}}</a>
						{% else %}
							<a href="{% url 'product:productList' %}?brand={{brand}}&pagenum={{page}}">{{page}}</a>
						{% endif %}
					{% endfor %}
					{% if endpage < pagecount %}
						<a href="{% url 'product:productList' %}?brand={{brand}}&pagenum={{startpage|add:pageblock}}"><i class="fa fa-long-arrow-right"></i></a>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
</section>
<!-- Product Section End -->
{%endblock%}