BeachMall/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from BeachMall import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('member/', include("member.urls")),
    path('product/', include("product.urls")),
    path('cart/', include("cart.urls")),
    path('wishlist/', include("wishlist.urls")),
    path('order/', include("order.urls")),
    path('survey/', include("survey.urls")),
    path('recommend/', include("recommend.urls")),
    path('refund/', include("refund.urls")),
    path('reviewboard/', include("reviewboard.urls")),
    path('noticeboard/', include("noticeboard.urls")),
    path('qnaboard/', include("qnaboard.urls")),
    path('search/', include('search_app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls.conf import path
from cart import views

app_name = "cart"

urlpatterns = [
    path("cart", views.CartView.as_view(), name="cart"),
    path("cartins", views.CartInsView.as_view(), name="cartins"),
    path("cartdel", views.CartDelView.as_view(), name="cartdel"),
    path("cartmod", views.CartModView.as_view(), name="cartmod"),
]

member/urls.py
from django.urls.conf import path
from member import views

app_name = "member"

urlpatterns = [
    path("login",views.LoginView.as_view(),name="login"),
    path('memberjoin', views.JoinView.as_view() ,name="memberjoin"),
    path("idconfirm", views.IdConfirmView.as_view(), name="idconfirm"), 
    path("telconfirm", views.TelConfirmView.as_view(), name="telconfirm"),
    path("logout", views.LogoutView.as_view(), name ="logout"),
    path("delete", views.DeleteView.as_view(), name="delete"), 
    path("modify", views.ModifyView.as_view(), name="modify"),
    path("modifypro", views.ModifyProView.as_view(), name="modifypro"),
    path("index",views.IndexView.as_view(), name="index"),
    path("myorderlist",views.MyOrderListView.as_view(), name="myorderlist"),
    path("myorderdetail",views.MyOrderDetailView.as_view(), name="myorderdetail"),
    path("mybeach",views.MyBeachView.as_view(), name="mybeach"),
    path("papup",views.PapUpView.as_view(), name="papup"),
]

product/urls.py
from django.urls.conf import path
from product import views

app_name = "product"

urlpatterns = [
    path("productDetail", views.ProductDetailView.as_view(), name="productDetail"),
    path("productCategory", views.ProductCategoryView.as_view(), name="productCategory"),
    path("productList", views.ProductListView.as_view(), name="productList"),
    path("waterRocket", views.WaterRocketView.as_view(), name="waterrocket"),
    ]

qnaboard/urls.py
from django.urls.conf import path
from qnaboard import views

app_name = "qnaboard"

urlpatterns = [
    path( "qna", views.ListView.as_view(), name="qna" ),
    path( "writearticle", views.WriteView.as_view(), name="writearticle" ),
    path( "detailarticle", views.DetailView.as_view(), name="detailarticle" ),
    path( "deletearticle", views.DeleteView.as_view(), name="deletearticle" ),
    path( "modifyarticle", views.ModifyView.as_view(), name="modifyarticle" ),
    path( "myQnaList", views.MyQnaList.as_view(), name="myQnaList" ),
    ]

refund/urls.py
from django.urls.conf import path
from refund import views
app_name="refund"
urlpatterns = [
    path('myrefundlist', views.RefundListView.as_view(),name="myrefundlist"),
    path('refundregister', views.RefundRegisterView.as_view(),name="refundregister"),   
]

wishlist/urls.py
from django.urls.conf import path
from wishlist import views

app_name = "wishlist"

urlpatterns = [
    path("wish", views.WishView.as_view(), name="wish"),
    path("wishdel", views.WishDelView.as_view(), name="wishdel"),
    path("wishins", views.WishInsView.as_view(), name="wishins"),
]

member/models.py
from django.db import models

# Create your models here.
class Member (models.Model):
    userId = models.CharField(max_length=50 , verbose_name="아이디", primary_key=True)
    passwd = models.CharField(max_length=50, verbose_name="비밀번호", null=False)
    name = models.CharField(max_length=50, verbose_name="이름", null=False)
    gender = models.CharField(max_length=6, verbose_name="성별", null=False)
    address = models.CharField(max_length=500, verbose_name="주소", null=True)
    detailaddr = models.CharField(max_length=500, verbose_name="디테일주소", null=True)
    zonecode = models.CharField(max_length=5, verbose_name="우편번호", null=True)
    email = models.CharField(max_length=500, verbose_name="이메일", null=True)
    tel = models.CharField(max_length=30, verbose_name="전화번호", null=True, unique=True)
    signupdate = models.DateTimeField(auto_now_add=True, verbose_name="가입일", null=False, blank=True)
    modifydate = models.DateTimeField(auto_now_add=True, verbose_name="최근 수정일", null=False, blank=True)
    status = models.CharField(max_length=500, verbose_name="가입상태", null=False)
    age = models.CharField(max_length=50, verbose_name="나이", null=False)

class DeleteMember (models.Model):
    userId = models.CharField(max_length=50 , verbose_name="아이디")
    name = models.CharField(max_length=50, verbose_name="이름", null=False)
    gender = models.CharField(max_length=6, verbose_name="성별", null=False)
    address = models.CharField(max_length=500, verbose_name="주소", null=True)
    detailaddr = models.CharField(max_length=500, verbose_name="디테일주소", null=True)
    zonecode = models.CharField(max_length=5, verbose_name="우편번호", null=True)
    email = models.CharField(max_length=500, verbose_name="이메일", null=True)
    tel = models.CharField(max_length=30, verbose_name="전화번호", null=True)
    signupdate = models.DateTimeField(verbose_name="가입일")

member/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from django.template import loader
from django.http.response import HttpResponse
from django.utils.dateformat import DateFormat
from member.models import Member, DeleteMember
from datetime import datetime, timedelta
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.core.exceptions import ObjectDoesNotExist
from django import template
from recommend.models import Recommend
from survey.models import Answer
from order.models import Order, OrderDetail
from product.models import Product
from cart.models import Cart
from refund.models import Refund
from product.choice import BRAND_CHOICE
import logging, csv
from static.myfunction import realtimeSearch, recommendByCartWishOrder, gender_age_recommend
import json

PAGE_SIZE = 5
PAGE_BLOCK = 3

logger = logging.getLogger(__name__)

#메인
class IndexView(View):
    def get (self,request):
        userId = request.session.get("memid")
        
        #로그를 이용해서 최근본 상품을 사용한다.
        productlog = open("log/productlog.log", 'r', encoding="utf-8")
        lines = csv.reader(productlog)  #전체 productlog하는 것을 갖고오는 것
        
        recents = []
        mostViews = {}
        count = 0
        today = datetime.today()
        for line in reversed(list(lines)):
            # 최대 일주일 치 로그만 분석한다.
            if datetime.strptime(line[0][1:11], "%Y-%m-%d") < today - timedelta(days=7):
                break
            id = line[3].split(":")[1]
            
            # 지금 로그인한 아이디에 관한 로그만 본다.
            if id != userId:
                continue
            
            # prodNum이 비어있으면 건너뛰기
            if line[4] == "" or line[4] == None:
                continue
            prodNum = line[4].split(":")[1]
            if Product.objects.filter(prodNum=prodNum).count() == 0:
                continue
            # 자주 본 상품번호 리스트에 집어넣기
            if str(prodNum) in mostViews:
                mostViews[str(prodNum)] += 1
            else:
                mostViews[str(prodNum)] = 1
            
            # 최근 본 상품번호 리스트에 집어넣기
            if count >= 4:
                continue
            else:
                if prodNum not in recents:
                    recents.append(prodNum)
                    count += 1
        
        # 상품 번호 리스트로 최근 본 상품
        recentProducts = [Product.objects.get(prodNum=recent) for recent in recents]
        
        views_sorted = [(key, value) for key, value in mostViews.items()][0:5]
        views_sorted.sort(key=lambda x:x[1], reverse=True)
        
        # 상품 번호 리스트로 자주 본 상품
        frequentProducts = [Product.objects.get(prodNum=prodNum) for prodNum, searchCount in views_sorted]
        
        productlog.close()
        
        # 연령대 및 성별로 추천 상품 추출
        gender_age_recos = []
        if userId:
            try:
                recos = Recommend.objects.filter(userId=userId).filter(status="gender_age").order_by("-recommendNum").first().prodList
                recommends = json.loads(recos)
                gender_age_recos = [Product.objects.get(prodNum=prodNum) for prodNum in recommends]
            except (ObjectDoesNotExist, AttributeError):
                gender_age_recos = []
        #OrderDetail.prodNum과 Product.prodNum 같은것을 연결해준. hotdeal객체를 사용하여 많이 구매한 상품을 띄어준다
        hotdeals = OrderDetail.objects.raw("""
        select od.orderDetailNum, od.orderNum, od.prodName, od.prodPrice, od.prodThumbnail, p.prodNum, p.brand
        from order_OrderDetail od, product_product p where od.prodNum=p.prodNum
        group by od.prodNum
        order by sum(buyCount) DESC LIMIT 5
        """)
        
        # 실시간 검색어
        rts = realtimeSearch()
        
        # 상품 구매 이력과 장바구니 추가이력으로 추천 상품
        ordercounts = Order.objects.filter(userId=userId).count()
        cartwishorder_recos = []
        if ordercounts > 0:
            try:
                recos = Recommend.objects.filter(userId=userId).filter(status="cart_wish_order").order_by("-recommendNum").first().prodList
                recommends = json.loads(recos)
                cartwishorder_recos = [Product.objects.get(prodNum=prodNum) for prodNum in recommends]
            except (ObjectDoesNotExist, AttributeError):
                cartwishorder_recos = []
        context={
            "cartwishorder_recos":cartwishorder_recos,
            "userId":userId,
            "recentProducts":recentProducts,
            "brands":BRAND_CHOICE,
            "frequentProducts":frequentProducts,
            "hotdeals":hotdeals,
            "gender_age_recos":gender_age_recos,
            "rts":rts,
            }
        template=loader.get_template("index.html")
        return HttpResponse(template.render( context ,request))
    def post(self,request):
        pass


#회원탈퇴
class DeleteView(View):
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(DeleteView, self).dispatch(request , *args, **kwargs)
    #get방식일때는 페이지만 넘기고 
    def get(self , request):
        template = loader.get_template("delete.html")
        context={}
        return HttpResponse(template.render(context,request))
    #post방식에서 유효성 검사를 해준다.
    def post(self , request):
        #userId를 Cookie에서 갖고온다
        userId = request.session.get("memid")
        #비밀번호를 입력받는다
        passwd = request.POST["passwd"]
        #Member모델에 컬럼이userId와 Cookie안에 memeid의 값이 같다면 
        dto = Member.objects.get(userId = userId)
         
        #비밀번호가 같다면 회원정보를 삭제된 회원 테이블에 넣어준다
        if passwd == dto.passwd :
            deletedto = DeleteMember(
                userId = dto.userId,
                name = dto.name,
                gender = dto.gender,
                address = dto.address,
                detailaddr =dto.address,
                email = dto.email,
                tel = dto.tel,
                signupdate = dto.signupdate 
            )
            # DeleteMember테이블에 탈퇴회원정보를 insert한다
            deletedto.save()
           
            dto.delete()        # member테이블에서 지워준다           
            del(request.session["memid"]) #로그아웃상태로 만들기
            return redirect("member:index")
        else: 
            #비밀번호가 다르면 생기는 페이지
            template = loader.get_template("delete.html")
            context={
                "message" : "비밀번호가 다릅니다.",
                }
            return HttpResponse(template.render(context, request))


#로그아웃을 만들어주는 View    
class LogoutView(View):
    def get (self,request):
        if request.session.get("memid"):
            del(request.session["memid"])
        return redirect("member:index")
    def post(self,request):
        pass

#로그인    
class LoginView(View):
    #post를 사용하기위해 먼저 정의해준다.
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(LoginView, self).dispatch(request , *args, **kwargs)
    def get(self, request):
        #쿠키에 memid가 있다면
        if request.session.get("memid"):
            #인덱스 페이지로 가라
            return redirect("member:index")
        #쿠키에 memid가 없다면
        else:
            #로그인 페이지그대로 존재
            template=loader.get_template("login.html")
            context={
                }
            return HttpResponse(template.render(context,request))
    def post(self, request):
        #입력받는값
        userId = request.POST["id"]
        passwd = request.POST["passwd"]
        
        #유효성 검사
        try:
            dto = Member.objects.get(userId=userId)
            # passwd가 Member테이블에 있는 것이라면 
            if passwd == dto.passwd:
                request.session["memid"] = userId  #db에있는 userId, passwd가  입력한것이 같다면  session (파이썬에서는 쿠키에)
                #설문지 조사테이블에 아이디가 있다면
                if Answer.objects.filter(userId = userId ):
                    #인덱스페이지로
                    return redirect("member:index")
                else:
                    #아이디가 인덱스페이지에 없다면
                    return redirect("survey:surveylist")
            else:
                message = "비밀번호가 다릅니다"
        except ObjectDoesNotExist:
            message ="아이디가 다릅니다"
            
        template= loader.get_template("login.html")
        
        context = {
            "message" :message
            }
        return HttpResponse(template.render(context, request))
    
#회원가입
class JoinView(View):
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(JoinView, self).dispatch(request , *args, **kwargs)
    
    # get방식 버튼을 입력할때
    def get(self,request):
        template = loader.get_template("join.html")
        context={
            }
        return HttpResponse(template.render(context,request))
    #입력 데이터 받는곳    
    def post(self,request):
        #templates에서 전화번호를 나눠준것을 받아서
        tel = ""
        tel1 = request.POST["tel1"]
        tel2 = request.POST["tel2"]
        tel3 = request.POST["tel3"]
        #다시 합쳐준다.
        if tel1 and tel2 and tel3 :
            tel = tel1  + "-" + tel2 + "-" + tel3
        email = ""
        email1 = request.POST["email1"]
        email2 = request.POST["email2"]
        if email1 and email2:
            email = email1  + "@" + email2
            
        dto = Member(
           userId = request.POST["id"],
           passwd = request.POST["passwd"],
           name = request.POST["name"],
           age = request.POST["age"],
           gender = request.POST["gender"],
           zonecode = request.POST["zonecode"],
           address = request.POST["addr"],
           detailaddr = request.POST["detailaddr"],
           email = email,
           # 짤라받는곳 붙여 받기
           tel = tel,
           signupdate = DateFormat(datetime.now()).format("Y-m-d") 
        )
        dto.save()
        #setting에서 info 에다 쌓이는것 

        return redirect("member:index") 

# 아이디 중복확인 체크
class IdConfirmView(View):
    def get(self, request):
        userId = request.GET["id"]  
        result = 0
        try :  
            # Member테이블에 아이디가 없다면 userId에 넣어준다

member/templates/myorderlist.html
{% extends "base.html"%}
{% load humanize %}
{% load mathfilters %}
<script src="https://kit.fontawesome.com/d0bb6518aa.js" crossorigin="anonymous"></script>

{% block navright %}
{% endblock %}

{%block content %}
{% if not request.session.memid %}
<script type="text/javascript">
	alert("로그인 후 이용하실 수 있습니다.");
	location.href = "{% url 'member:login' %}"
</script>
{% else %}
<script type="text/javascript">
	function insertcart(userId, prodNum){
		location.href = "{% url 'cart:cartins' %}?userId="+userId+"&prodNum="+prodNum+"&buyCount=1";
	}
</script>
<!-- 리뷰 작성 모달 -->
<div class="modal fade" id="writeReview" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
        	<form name="reviewform" method="post" enctype="multipart/form-data" action="{% url 'reviewboard:reviewWrite' %}" onsubmit="return reviewcheck()">
				<input type="hidden" name="prodNum" value="">
				<input type="hidden" name="userId" value="{{request.session.memid}}">
				<div class="modal-header">
					<h4 class="modal-title">리뷰 작성</h4>
					<button type="button" class="close" data-dismiss="modal">×</button>
				</div>
				<div class="modal-body">
					<table>
						<tr>
							<th>상품명</th>
							<td><input type="text" name="prodName" readonly></td>
						</tr>
						<tr>
							<th>제목<span style="color:red;">*</span></th>
							<td><input type="text" name="reviewTitle"></td>
						</tr>
						<tr>
							<th>내용<span style="color:red;">*</span></th>
							<td><textarea name="reviewContent" rows="10" cols="35"></textarea></td>
						</tr>
						<tr>
							<th>사진</th>
							<td><input type="file" name="reviewPhoto"></td>
						</tr>
					</table>
					<br>
					<h6 class="modal-title"><span style="color:red;">*</span>는 필수 입력 항목입니다.</h6>
				</div>
				<div class="modal-footer">
					<p> 리뷰를 등록할까요? </p>
					<input style="width:50px;"class="inputbutton" type="submit" value="예">
					<input class="inputbutton" type="button" value="아니오" class="close" data-dismiss="modal">
		        </div>
            </form>
        </div>
    </div>
</div>

<div style="min-height: 100%; position: relative;">
	<main class="main_mypage">
		<div class="mybeach">My비치</div>
		<section id="main_section">
			<div class="mainwarp">
				<!-- 마이비치 메뉴-->
				<div class="navleftwarp">
					<div>
						<div style="">
							<nav style="">
								<div class="navtext">
									<div>My 쇼핑</div>
									<div class="navtext_div">
										<ul>
											<li class="mylist_select1"><a href="{% url 'member:myorderlist' %}">주문목록</a></li>
											<li class="mylist_select1"><a href="{% url 'reviewboard:myReviewList' %}">나의 리뷰목록</a></li>
											<li class="mylist_select1"><a href="{% url 'qnaboard:myQnaList' %}">나의 질문목록</a></li>
											<li class="mylist_select2"><a href="{% url 'refund:myrefundlist' %}">반품/환불/교환내역</a></li>
											<li class="mylist_select2"><a href="{% url 'member:modify' %}">개인정보 확인/수정</a></li>
											<li class="mylist_select2"><a href="{% url 'member:delete' %}">회원탈퇴</a></li>
										</ul>
									</div>
								</div>
								<div></div>
							</nav>
						</div>
					</div>
				</div>
				<!-- 마이비치 메뉴 끝-->
				<div class="contentwrap">
				{% if ordercount == 0 %}
					구매하신 물품이 없습니다
				{% else %}
				{% for order, orderdetails in orderlist %}
					<div class="contentwarp_size">
						<div
							style="height: 28px; display: flex; justify-content: space-between; -webkit-box-pack: justify;">
							<div class="after_order_date_css">{{ order.orderDate|date:"Y-m-d D H:i" }} 주문</div>
							<div class="after_order_detailmom_css">
								<span><a href="{% url 'member:myorderdetail' %}?orderNum={{order.orderNum}}">주문 상세보기</a></span>
							</div>
						</div>
						{% for orderdetail, refund in orderdetails %}
						<div class="after_order">
							<div>
								<div>
									<span class="after_order_baesong_font">배송완료</span> <span>&nbsp;</span>
									<span class="after_order_baesong_date_font"></span>
								</div>
							</div>
							<table class="after_order_table">
								<colgroup>
									<col width="600px">
									<col width="">
								</colgroup>
								<tbody class="after_order_tbody">
									<tr>
										<td class="after_td_title">
											<div class="after_td_divnull"></div>
											<div>
												<div
													style="margin-top: 20px; box-sizing: border-box; overflow: hidden;">
													<div
														style="overflow: hidden; display: flex; flex-direction: row;">
														<div class="after_order_div_img">
															<a href=""><img src="{{orderdetail.prodThumbnail}}" alt=""></a>
														</div>
														<div class="after_order_div_prodname_mom">
															<div class="after_order_div_prodname">
																<a class="after_order_prod_a" href="{% url 'product:productDetail' %}?prodNum={{orderdetail.prodNum}}">
																	<span class="after_order_prodname_span_Tname">
																		{{ orderdetail.prodName }}
																	</span>
																</a>
																<a class="after_order_prodprice" href="{% url 'product:productDetail' %}?prodNum={{orderdetail.prodNum}}">
																	<div style="box-sizing: border-box;">
																		<div class="after_order_prodprice2">
																			<span style="font-size: 1rem; font-weight: normal; box-sizing: border-box;">
																				{{ orderdetail.prodPrice|intcomma }}원
																			</span>
																			<span class="after_order_nullspan">
																				<span class="after_order_nullspanspan"></span>
																			</span>
																			<span style="font-size: 1rem;">{{ orderdetail.buyCount }}개</span>
																		</div>
																	</div>
																</a>
																<div style="box-sizing: border-box;">
																	<button class="after_order_prod_cart" onclick="insertcart('{{order.userId}}', {{orderdetail.prodNum}})">장바구니 담기</button>
																	<div class="after_order_nulldiv"></div>
																</div>
																<div class="after_order_null_div"></div>
															</div>
														</div>
													</div>
												</div>
											</div>
										</td>
										<td class="after_td_sh_od">
											<div class="after_td_sh_od_div">
												<button class="after_td_sh_od_div_button1">배송완료</button>
												{% if refund == 'y' %}
												<button class="after_td_sh_od_div_button2" disabled>이미 처리된 상품입니다.</button>
												{% elif refund == 'n' %}
												<button class="after_td_sh_od_div_button2" disabled>반품/환불/교환 진행중</button>
												{% else %}
												<button class="after_td_sh_od_div_button2"
													onclick="location='{% url 'refund:refundregister' %}?orderDetailNum={{orderdetail.orderDetailNum}}'">반품/환불/교환</button>
												{% endif %}
												<button class="after_td_sh_od_div_button2" data-toggle="modal" data-target="#writeReview"
													onclick="writereview('{{orderdetail.prodNum}}', '{{orderdetail.prodName}}', '{{order.orderDate}}')">리뷰 작성하기</button>
											</div>
										</td>
									</tr>
								</tbody>
							</table>
						</div>
						{% endfor %}
					</div>
				{% endfor %}
					<!-- 주문목록 페이지 이동 버튼 -->
					<div class="contentwarp_size_button_mom">
						<ul class="pagination">
							{% if startpage > pageblock %}
								<li class="page-item"><a class="page-link" href="% url 'member:myorderlist' %}?pagenum={{startpage|sub:pageblock}}">이전</a></li>
							{% endif %}
							{% for page in pages %}
								{% if pagenum == page %}
								<li class="page-item disabled"><a class="page-link " href="#">{{page}}</a></li>
								{% else %}
								<li class="page-item"><a class="page-link" href="{% url 'member:myorderlist' %}?pagenum={{page}}">{{page}}</a></li>
								{% endif %}
							{% endfor %}
							{% if endpage < pagecount %}
								<li class="page-item"><a class="page-link" href="{% url 'member:myorderlist' %}?pagenum={{startpage|add:pageblock}}">다음</a></li>
							{% endif %}
						</ul>
					</div>
				{% endif %}
				</div>
				<div
					style="background-color: rgb(255, 255, 255); margin-top: 30px; padding: 30px 30px;">
					<div class="sc-178zqvr-11 UxXQy"
						style="width: 930px; margin-left: 170px;">
						<div>
							<b> <i class="sc-178zqvr-13 bQUraS"></i> <span
								class="i18n-wrapper"> <span style="color: #e52628;">&nbsp;취소/반품/교환
										신청</span>전 확인해주세요!
							</span>
							</b>
						</div>
						<div class="sc-178zqvr-14 bboIjZ">
							<strong class="sc-178zqvr-15 fWZpfp">취소</strong>
						</div>
						<div class="sc-178zqvr-14 bboIjZ">
							- <span class="i18n-wrapper">여행/레저/숙박 상품은 취소 시 수수료가 발생할 수
								있으며,<br> <span style="margin-left: 7px;">취소수수료를 확인하여
									2일 이내(주말,공휴일 제외) 처리결과를 문자로 안내해드립니다.</span>
							</span>(
							<!-- -->
							당일 접수 기준, 마감시간 오후 4시
							<!-- -->
							)
						</div>
						<div class="sc-178zqvr-14 bboIjZ">
							-
							<!-- -->
							문화 상품은 사용 전날 24시까지 취소 신청 시 취소수수료가 발생되지 않습니다.
						</div>
						<div class="sc-178zqvr-14 bboIjZ">
							<strong class="sc-178zqvr-15 fWZpfp">반품</strong>
						</div>
						<div class="sc-178zqvr-14 bboIjZ">
							-
							<!-- -->
							상품 수령 후 7일 이내 신청하여 주세요.
						</div>
						<div class="sc-178zqvr-14 bboIjZ">
							-
							<!-- -->
							<!-- -->
							상품이 출고된 이후에는 배송 완료 후, 반품 상품을 회수합니다.
						</div>
						<div class="sc-178zqvr-14 bboIjZ">
							-
							<!-- -->
							<!-- -->
							설치상품/주문제작/해외배송/신선냉동 상품 등은 고객센터에서만 반품 신청이 가능합니다.
							<!-- -->
							<a href="/ssr/desktop/contact/inquiry" target="_blank"
								class="sc-178zqvr-16 jgRggD">1:1문의하기</a>
						</div>
						<div class="sc-178zqvr-14 bboIjZ">
							<strong class="sc-178zqvr-15 fWZpfp">교환</strong>
						</div>
						<div class="sc-178zqvr-14 bboIjZ">
							-
							<!-- -->
							<!-- -->
							상품의 교환 신청은 고객센터로 문의하여 주세요.<a href="/ssr/desktop/contact/inquiry"
								target="_blank" class="sc-178zqvr-16 jgRggD">1:1문의하기</a>
						</div>
					</div>
				</div>
				<div class="sc-zlsu1d-0 sc-s18rof-0 gAsjwR dqjcud"
					style="margin-top: 0px;">
					<img style="margin-left: 200px; width: 910px;"
						src="../static/images/is_water.jpg">
				</div>
			</div>

		</section>

	</main>
	<div
		style="text-align: center; position: relative; margin-top: 50px; margin-bottom: 50px;">10월
		푸르구나</div>
</div>
{% endif %}
{% endblock %}

member/templates/papup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>pap_up</title>
</head>
<body>
    <img src="../static/images/pap.png" usemap="#pap" alt="event page">
    <map name="pap" id="pap">
        <area shape="rect" coords="380,457,487,492" href="#"
        alt="showpap" onclick="showpap();">
    </map>   
</body>
</html>